[project]
name = "taxi-prediction-fullstack-daniel-opa24"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.2",
    "pandas>=2.3.2",
    "setuptools>=80.9.0",
    "streamlit>=1.49.1",
    "uvicorn>=0.35.0",
]
